services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shorturl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
  
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: analytics_service
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8082:8082" 
    environment:
    - JAVA_OPTS_APPEND=-Dquarkus.profile=docker

  url-service:
    build:
      context: ./url-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: url_service
    depends_on:
      - postgres
      - keycloak
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
    - JAVA_OPTS_APPEND=-Dquarkus.profile=docker -Duser.timezone=America/Argentina/Buenos_Aires
  
  gateway:
    build:
      context: ./gateway
    ports:
      - "8081:8081"
    depends_on:
      - url-service
      - keycloak
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/smartlink-hub
      - SPRING_CLOUD_GATEWAY_ROUTES_0_URI=http://url-service:8080
      - SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0=Path=/api/urls/**

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret

  ai-service:
    build: 
      context: ./ai-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: ai-service
    ports:
      - "8083:8083"
    environment:
      - QUARKUS_LANGCHAIN4J_AI_GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - url-service
      
volumes:
  postgres_data:
  keycloak_data:
  rabbitmq_data: