quarkus.http.port=8083

quarkus.langchain4j.ai.gemini.api-key=${GEMINI_API_KEY}
quarkus.langchain4j.ai.gemini.model-name=gemini-1.5-flash
quarkus.langchain4j.ai.gemini.timeout=10s

quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.otel.traces.sampler=parentbased_traceidratio
quarkus.otel.traces.sampler.arg=1.0
quarkus.otel.service.name=ai-service

# Formato JSON para Promtail/Loki
quarkus.log.console.json=true
quarkus.log.console.json.pretty-print=false
quarkus.log.console.json.exception-output-type=formatted

# Campos útiles para Loki labels/queries
quarkus.log.console.json.additional-field.service=ai-service
quarkus.log.console.json.additional-field.environment=local

%docker.quarkus.otel.exporter.otlp.traces.endpoint=http://jaeger:4317
%docker.quarkus.log.console.json.additional-field.environment=docker
