quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/shorturl
quarkus.jvm-args=-Duser.timezone=America/Argentina/Buenos_Aires
quarkus.swagger-ui.path=/docs
quarkus.hibernate-orm.database.generation=update