quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/shorturl
quarkus.swagger-ui.path=/docs
quarkus.hibernate-orm.database.generation=update

quarkus.oidc.auth-server-url=http://localhost:8180/realms/smartlink-hub
quarkus.oidc.application-type=service
quarkus.oidc.client-id=smartlink-gateway

# Conector RabbitMQ
mp.messaging.outgoing.url_clicked.connector=smallrye-rabbitmq
mp.messaging.outgoing.url_clicked.host=localhost
mp.messaging.outgoing.url_clicked.port=5672
mp.messaging.outgoing.url_clicked.username=admin
mp.messaging.outgoing.url_clicked.password=secret
mp.messaging.outgoing.url_clicked.exchange.name=url_clicked_exchange
mp.messaging.outgoing.url_clicked.exchange.type=direct
mp.messaging.outgoing.url_clicked.routing-key=url_clicked

quarkus.devservices.enabled=false

## Properties for Docker enviroment:
%docker.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/shorturl

%docker.quarkus.oidc.auth-server-url=http://keycloak:8080/realms/smartlink-hub

%docker.mp.messaging.outgoing.url_clicked.host=rabbitmq