quarkus.http.port=8082
quarkus.swagger-ui.path=/docs

quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=smartlink
#quarkus.hibernate-orm.database.generation=update

quarkus.devservices.enabled=false

# Conector RabbitMQ
mp.messaging.incoming.url_clicked.connector=smallrye-rabbitmq
mp.messaging.incoming.url_clicked.host=localhost
mp.messaging.incoming.url_clicked.port=5672
mp.messaging.incoming.url_clicked.username=admin
mp.messaging.incoming.url_clicked.password=secret
mp.messaging.incoming.url_clicked.exchange.name=url_clicked_exchange
mp.messaging.incoming.url_clicked.queue.name=url_clicked_queue
mp.messaging.incoming.url_clicked.routing-key=url_clicked
mp.messaging.incoming.url_clicked.exchange.declare=false
mp.messaging.incoming.url_clicked.queue.declare=false
mp.messaging.incoming.url_clicked.queue.bind=false
mp.messaging.incoming.url-clicked.failure-strategy=dead-letter-queue
mp.messaging.incoming.url-clicked.dead-letter-queue.exchange.name=url-clicked-dlq

# For RabbitMQConfig file
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=admin
rabbitmq.password=secret
rabbitmq.exchange=url_clicked_exchange
rabbitmq.queue=url_clicked_queue
rabbitmq.routing-key=url_clicked

## Properties for Docker enviroment:
%docker.mp.messaging.incoming.url_clicked.host=rabbitmq
%docker.rabbitmq.host=rabbitmq
%docker.quarkus.mongodb.connection-string=mongodb://mongo:27017
